from db_structure import *
from adding_tools import new_university
from adding_tools import new_faculty
from adding_tools import new_department
#from adding_tools import new_stream
from adding_tools import new_group
from adding_tools import new_degree
from adding_tools import new_teacher
from adding_tools import new_room
from adding_tools import new_subject
from adding_tools import add_lesson_plan
from adding_tools import new_lesson
from adding_tools import new_tmp_lesson
from select_tools import select_universities
from select_tools import select_faculties
from select_tools import select_departments
from select_tools import select_groups
from select_tools import select_degees
from select_tools import select_teachers
from select_tools import select_rooms
from select_tools import select_subject
from select_tools import select_lesson_types
from select_tools import select_lesson_times
from select_tools import select_week_days
from select_tools import select_weeks
from select_tools import select_lesson_plans
from select_tools import select_lessons
from select_tools import select_tmp_lessons
from update_tools import update_university
from update_tools import update_faculty
from update_tools import update_department
from update_tools import update_group
from update_tools import update_degree
from update_tools import update_teacher
from update_tools import update_room
from update_tools import update_subject
from update_tools import update_lesson_plan
from update_tools import update_lesson
from update_tools import update_tmp_lesson
from delete_tools import delete_university
from delete_tools import delete_faculty
from delete_tools import delete_department
from delete_tools import delete_group
from delete_tools import delete_degree
from delete_tools import delete_teacher
from delete_tools import delete_room
from delete_tools import delete_subject
from delete_tools import delete_lesson_plan
from delete_tools import delete_lesson
from delete_tools import delete_tmp_lesson
