# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'full_table.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(819, 519)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_126 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.pushButton_126.setSizePolicy(sizePolicy)
        self.pushButton_126.setAcceptDrops(True)
        self.pushButton_126.setObjectName(_fromUtf8("pushButton_126"))
        self.gridLayout.addWidget(self.pushButton_126, 6, 4, 1, 1)
        self.pushButton_135 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.pushButton_135.setSizePolicy(sizePolicy)
        self.pushButton_135.setAcceptDrops(True)
        self.pushButton_135.setObjectName(_fromUtf8("pushButton_135"))
        self.gridLayout.addWidget(self.pushButton_135, 9, 5, 1, 1)
        self.pushButton_125 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.pushButton_125.setSizePolicy(sizePolicy)
        self.pushButton_125.setAcceptDrops(True)
        self.pushButton_125.setObjectName(_fromUtf8("pushButton_125"))
        self.gridLayout.addWidget(self.pushButton_125, 6, 2, 1, 1)
        self.pushButton_124 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.pushButton_124.setSizePolicy(sizePolicy)
        self.pushButton_124.setAcceptDrops(True)
        self.pushButton_124.setObjectName(_fromUtf8("pushButton_124"))
        self.gridLayout.addWidget(self.pushButton_124, 4, 3, 1, 1)
        self.pushButton_118 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.pushButton_118.setSizePolicy(sizePolicy)
        self.pushButton_118.setAcceptDrops(True)
        self.pushButton_118.setObjectName(_fromUtf8("pushButton_118"))
        self.gridLayout.addWidget(self.pushButton_118, 8, 0, 1, 1)
        self.pushButton_130 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_130.sizePolicy().hasHeightForWidth())
        self.pushButton_130.setSizePolicy(sizePolicy)
        self.pushButton_130.setAcceptDrops(True)
        self.pushButton_130.setObjectName(_fromUtf8("pushButton_130"))
        self.gridLayout.addWidget(self.pushButton_130, 7, 3, 1, 1)
        self.pushButton_132 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_132.sizePolicy().hasHeightForWidth())
        self.pushButton_132.setSizePolicy(sizePolicy)
        self.pushButton_132.setAcceptDrops(True)
        self.pushButton_132.setObjectName(_fromUtf8("pushButton_132"))
        self.gridLayout.addWidget(self.pushButton_132, 8, 3, 1, 1)
        self.pushButton_138 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_138.sizePolicy().hasHeightForWidth())
        self.pushButton_138.setSizePolicy(sizePolicy)
        self.pushButton_138.setAcceptDrops(True)
        self.pushButton_138.setObjectName(_fromUtf8("pushButton_138"))
        self.gridLayout.addWidget(self.pushButton_138, 8, 2, 1, 1)
        self.pushButton_116 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_116.sizePolicy().hasHeightForWidth())
        self.pushButton_116.setSizePolicy(sizePolicy)
        self.pushButton_116.setAcceptDrops(True)
        self.pushButton_116.setObjectName(_fromUtf8("pushButton_116"))
        self.gridLayout.addWidget(self.pushButton_116, 6, 3, 1, 1)
        self.pushButton_122 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_122.sizePolicy().hasHeightForWidth())
        self.pushButton_122.setSizePolicy(sizePolicy)
        self.pushButton_122.setAcceptDrops(True)
        self.pushButton_122.setObjectName(_fromUtf8("pushButton_122"))
        self.gridLayout.addWidget(self.pushButton_122, 7, 0, 1, 1)
        self.pushButton_129 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_129.sizePolicy().hasHeightForWidth())
        self.pushButton_129.setSizePolicy(sizePolicy)
        self.pushButton_129.setAcceptDrops(True)
        self.pushButton_129.setObjectName(_fromUtf8("pushButton_129"))
        self.gridLayout.addWidget(self.pushButton_129, 4, 5, 1, 1)
        self.pushButton_123 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_123.sizePolicy().hasHeightForWidth())
        self.pushButton_123.setSizePolicy(sizePolicy)
        self.pushButton_123.setAcceptDrops(True)
        self.pushButton_123.setObjectName(_fromUtf8("pushButton_123"))
        self.gridLayout.addWidget(self.pushButton_123, 9, 1, 1, 1)
        self.pushButton_133 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_133.sizePolicy().hasHeightForWidth())
        self.pushButton_133.setSizePolicy(sizePolicy)
        self.pushButton_133.setAcceptDrops(True)
        self.pushButton_133.setObjectName(_fromUtf8("pushButton_133"))
        self.gridLayout.addWidget(self.pushButton_133, 8, 5, 1, 1)
        self.pushButton_134 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_134.sizePolicy().hasHeightForWidth())
        self.pushButton_134.setSizePolicy(sizePolicy)
        self.pushButton_134.setAcceptDrops(True)
        self.pushButton_134.setObjectName(_fromUtf8("pushButton_134"))
        self.gridLayout.addWidget(self.pushButton_134, 8, 4, 1, 1)
        self.pushButton_111 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_111.sizePolicy().hasHeightForWidth())
        self.pushButton_111.setSizePolicy(sizePolicy)
        self.pushButton_111.setAcceptDrops(True)
        self.pushButton_111.setObjectName(_fromUtf8("pushButton_111"))
        self.gridLayout.addWidget(self.pushButton_111, 4, 0, 1, 1)
        self.pushButton_114 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_114.sizePolicy().hasHeightForWidth())
        self.pushButton_114.setSizePolicy(sizePolicy)
        self.pushButton_114.setAcceptDrops(True)
        self.pushButton_114.setObjectName(_fromUtf8("pushButton_114"))
        self.gridLayout.addWidget(self.pushButton_114, 4, 2, 1, 1)
        self.pushButton_127 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_127.sizePolicy().hasHeightForWidth())
        self.pushButton_127.setSizePolicy(sizePolicy)
        self.pushButton_127.setAcceptDrops(True)
        self.pushButton_127.setObjectName(_fromUtf8("pushButton_127"))
        self.gridLayout.addWidget(self.pushButton_127, 9, 4, 1, 1)
        self.pushButton_136 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_136.sizePolicy().hasHeightForWidth())
        self.pushButton_136.setSizePolicy(sizePolicy)
        self.pushButton_136.setAcceptDrops(True)
        self.pushButton_136.setObjectName(_fromUtf8("pushButton_136"))
        self.gridLayout.addWidget(self.pushButton_136, 4, 4, 1, 1)
        self.pushButton_119 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_119.sizePolicy().hasHeightForWidth())
        self.pushButton_119.setSizePolicy(sizePolicy)
        self.pushButton_119.setAcceptDrops(True)
        self.pushButton_119.setObjectName(_fromUtf8("pushButton_119"))
        self.gridLayout.addWidget(self.pushButton_119, 7, 5, 1, 1)
        self.pushButton_120 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_120.sizePolicy().hasHeightForWidth())
        self.pushButton_120.setSizePolicy(sizePolicy)
        self.pushButton_120.setAcceptDrops(True)
        self.pushButton_120.setObjectName(_fromUtf8("pushButton_120"))
        self.gridLayout.addWidget(self.pushButton_120, 9, 3, 1, 1)
        self.pushButton_117 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_117.sizePolicy().hasHeightForWidth())
        self.pushButton_117.setSizePolicy(sizePolicy)
        self.pushButton_117.setAcceptDrops(True)
        self.pushButton_117.setObjectName(_fromUtf8("pushButton_117"))
        self.gridLayout.addWidget(self.pushButton_117, 9, 2, 1, 1)
        self.pushButton_128 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_128.sizePolicy().hasHeightForWidth())
        self.pushButton_128.setSizePolicy(sizePolicy)
        self.pushButton_128.setAcceptDrops(True)
        self.pushButton_128.setObjectName(_fromUtf8("pushButton_128"))
        self.gridLayout.addWidget(self.pushButton_128, 7, 1, 1, 1)
        self.pushButton_121 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_121.sizePolicy().hasHeightForWidth())
        self.pushButton_121.setSizePolicy(sizePolicy)
        self.pushButton_121.setAcceptDrops(True)
        self.pushButton_121.setObjectName(_fromUtf8("pushButton_121"))
        self.gridLayout.addWidget(self.pushButton_121, 7, 4, 1, 1)
        self.pushButton_115 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_115.sizePolicy().hasHeightForWidth())
        self.pushButton_115.setSizePolicy(sizePolicy)
        self.pushButton_115.setAcceptDrops(True)
        self.pushButton_115.setObjectName(_fromUtf8("pushButton_115"))
        self.gridLayout.addWidget(self.pushButton_115, 8, 1, 1, 1)
        self.pushButton_139 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_139.sizePolicy().hasHeightForWidth())
        self.pushButton_139.setSizePolicy(sizePolicy)
        self.pushButton_139.setAcceptDrops(True)
        self.pushButton_139.setObjectName(_fromUtf8("pushButton_139"))
        self.gridLayout.addWidget(self.pushButton_139, 6, 1, 1, 1)
        self.pushButton_112 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_112.sizePolicy().hasHeightForWidth())
        self.pushButton_112.setSizePolicy(sizePolicy)
        self.pushButton_112.setAcceptDrops(True)
        self.pushButton_112.setObjectName(_fromUtf8("pushButton_112"))
        self.gridLayout.addWidget(self.pushButton_112, 6, 0, 1, 1)
        self.pushButton_131 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_131.sizePolicy().hasHeightForWidth())
        self.pushButton_131.setSizePolicy(sizePolicy)
        self.pushButton_131.setAcceptDrops(True)
        self.pushButton_131.setObjectName(_fromUtf8("pushButton_131"))
        self.gridLayout.addWidget(self.pushButton_131, 6, 5, 1, 1)
        self.pushButton_137 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_137.sizePolicy().hasHeightForWidth())
        self.pushButton_137.setSizePolicy(sizePolicy)
        self.pushButton_137.setAcceptDrops(True)
        self.pushButton_137.setObjectName(_fromUtf8("pushButton_137"))
        self.gridLayout.addWidget(self.pushButton_137, 7, 2, 1, 1)
        self.pushButton_113 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_113.sizePolicy().hasHeightForWidth())
        self.pushButton_113.setSizePolicy(sizePolicy)
        self.pushButton_113.setAcceptDrops(True)
        self.pushButton_113.setObjectName(_fromUtf8("pushButton_113"))
        self.gridLayout.addWidget(self.pushButton_113, 9, 0, 1, 1)
        self.pushButton_110 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_110.sizePolicy().hasHeightForWidth())
        self.pushButton_110.setSizePolicy(sizePolicy)
        self.pushButton_110.setAcceptDrops(True)
        self.pushButton_110.setObjectName(_fromUtf8("pushButton_110"))
        self.gridLayout.addWidget(self.pushButton_110, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton_126.setText(_translate("Form", "PushButton", None))
        self.pushButton_135.setText(_translate("Form", "PushButton", None))
        self.pushButton_125.setText(_translate("Form", "PushButton", None))
        self.pushButton_124.setText(_translate("Form", "PushButton", None))
        self.pushButton_118.setText(_translate("Form", "PushButton", None))
        self.pushButton_130.setText(_translate("Form", "PushButton", None))
        self.pushButton_132.setText(_translate("Form", "PushButton", None))
        self.pushButton_138.setText(_translate("Form", "PushButton", None))
        self.pushButton_116.setText(_translate("Form", "PushButton", None))
        self.pushButton_122.setText(_translate("Form", "PushButton", None))
        self.pushButton_129.setText(_translate("Form", "PushButton", None))
        self.pushButton_123.setText(_translate("Form", "PushButton", None))
        self.pushButton_133.setText(_translate("Form", "PushButton", None))
        self.pushButton_134.setText(_translate("Form", "PushButton", None))
        self.pushButton_111.setText(_translate("Form", "PushButton", None))
        self.pushButton_114.setText(_translate("Form", "PushButton", None))
        self.pushButton_127.setText(_translate("Form", "PushButton", None))
        self.pushButton_136.setText(_translate("Form", "PushButton", None))
        self.pushButton_119.setText(_translate("Form", "PushButton", None))
        self.pushButton_120.setText(_translate("Form", "PushButton", None))
        self.pushButton_117.setText(_translate("Form", "PushButton", None))
        self.pushButton_128.setText(_translate("Form", "PushButton", None))
        self.pushButton_121.setText(_translate("Form", "PushButton", None))
        self.pushButton_115.setText(_translate("Form", "PushButton", None))
        self.pushButton_139.setText(_translate("Form", "PushButton", None))
        self.pushButton_112.setText(_translate("Form", "PushButton", None))
        self.pushButton_131.setText(_translate("Form", "PushButton", None))
        self.pushButton_137.setText(_translate("Form", "PushButton", None))
        self.pushButton_113.setText(_translate("Form", "PushButton", None))
        self.pushButton_110.setText(_translate("Form", "PushButton", None))

