from adding_tools import new_university
from adding_tools import new_faculty
from adding_tools import new_department
#from adding_tools import new_stream
from adding_tools import new_group
from adding_tools import new_degree
from adding_tools import new_teacher
from adding_tools import new_room
from adding_tools import new_subject
from adding_tools import add_lesson_plan
from adding_tools import new_lesson
from adding_tools import new_tmp_lesson
