# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bit_table.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(805, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setMouseTracking(True)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 2)
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_7 = QtGui.QSplitter(self.tab_2)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.splitter = QtGui.QSplitter(self.splitter_7)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pushButton = QtGui.QPushButton(self.splitter)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.splitter)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.splitter)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.splitter)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.splitter)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.splitter_6 = QtGui.QSplitter(self.splitter_7)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.pushButton_26 = QtGui.QPushButton(self.splitter_6)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.pushButton_27 = QtGui.QPushButton(self.splitter_6)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.pushButton_28 = QtGui.QPushButton(self.splitter_6)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.pushButton_29 = QtGui.QPushButton(self.splitter_6)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.pushButton_30 = QtGui.QPushButton(self.splitter_6)
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.splitter_5 = QtGui.QSplitter(self.splitter_7)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.pushButton_21 = QtGui.QPushButton(self.splitter_5)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_22 = QtGui.QPushButton(self.splitter_5)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_23 = QtGui.QPushButton(self.splitter_5)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.pushButton_24 = QtGui.QPushButton(self.splitter_5)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(self.splitter_5)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_7)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pushButton_6 = QtGui.QPushButton(self.splitter_2)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.splitter_2)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.splitter_2)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.splitter_2)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.splitter_2)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_7)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.pushButton_11 = QtGui.QPushButton(self.splitter_3)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.splitter_3)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.splitter_3)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.splitter_3)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.splitter_3)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.splitter_4 = QtGui.QSplitter(self.splitter_7)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.pushButton_16 = QtGui.QPushButton(self.splitter_4)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.splitter_4)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.splitter_4)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.splitter_4)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.pushButton_20 = QtGui.QPushButton(self.splitter_4)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.verticalLayout_2.addWidget(self.splitter_7)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_31 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.verticalLayout_3.addWidget(self.pushButton_31)
        self.pushButton_35 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_35.sizePolicy().hasHeightForWidth())
        self.pushButton_35.setSizePolicy(sizePolicy)
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.verticalLayout_3.addWidget(self.pushButton_35)
        self.pushButton_32 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.verticalLayout_3.addWidget(self.pushButton_32)
        self.pushButton_34 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_34.sizePolicy().hasHeightForWidth())
        self.pushButton_34.setSizePolicy(sizePolicy)
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.verticalLayout_3.addWidget(self.pushButton_34)
        self.pushButton_33 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.verticalLayout_3.addWidget(self.pushButton_33)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.pushButton_66 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_66.sizePolicy().hasHeightForWidth())
        self.pushButton_66.setSizePolicy(sizePolicy)
        self.pushButton_66.setObjectName(_fromUtf8("pushButton_66"))
        self.verticalLayout_10.addWidget(self.pushButton_66)
        self.pushButton_67 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_67.sizePolicy().hasHeightForWidth())
        self.pushButton_67.setSizePolicy(sizePolicy)
        self.pushButton_67.setObjectName(_fromUtf8("pushButton_67"))
        self.verticalLayout_10.addWidget(self.pushButton_67)
        self.pushButton_68 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_68.sizePolicy().hasHeightForWidth())
        self.pushButton_68.setSizePolicy(sizePolicy)
        self.pushButton_68.setObjectName(_fromUtf8("pushButton_68"))
        self.verticalLayout_10.addWidget(self.pushButton_68)
        self.pushButton_69 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_69.sizePolicy().hasHeightForWidth())
        self.pushButton_69.setSizePolicy(sizePolicy)
        self.pushButton_69.setObjectName(_fromUtf8("pushButton_69"))
        self.verticalLayout_10.addWidget(self.pushButton_69)
        self.pushButton_70 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_70.sizePolicy().hasHeightForWidth())
        self.pushButton_70.setSizePolicy(sizePolicy)
        self.pushButton_70.setObjectName(_fromUtf8("pushButton_70"))
        self.verticalLayout_10.addWidget(self.pushButton_70)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.pushButton_61 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_61.sizePolicy().hasHeightForWidth())
        self.pushButton_61.setSizePolicy(sizePolicy)
        self.pushButton_61.setObjectName(_fromUtf8("pushButton_61"))
        self.verticalLayout_9.addWidget(self.pushButton_61)
        self.pushButton_62 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_62.sizePolicy().hasHeightForWidth())
        self.pushButton_62.setSizePolicy(sizePolicy)
        self.pushButton_62.setObjectName(_fromUtf8("pushButton_62"))
        self.verticalLayout_9.addWidget(self.pushButton_62)
        self.pushButton_63 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_63.sizePolicy().hasHeightForWidth())
        self.pushButton_63.setSizePolicy(sizePolicy)
        self.pushButton_63.setObjectName(_fromUtf8("pushButton_63"))
        self.verticalLayout_9.addWidget(self.pushButton_63)
        self.pushButton_64 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_64.sizePolicy().hasHeightForWidth())
        self.pushButton_64.setSizePolicy(sizePolicy)
        self.pushButton_64.setObjectName(_fromUtf8("pushButton_64"))
        self.verticalLayout_9.addWidget(self.pushButton_64)
        self.pushButton_65 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_65.sizePolicy().hasHeightForWidth())
        self.pushButton_65.setSizePolicy(sizePolicy)
        self.pushButton_65.setObjectName(_fromUtf8("pushButton_65"))
        self.verticalLayout_9.addWidget(self.pushButton_65)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButton_71 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_71.sizePolicy().hasHeightForWidth())
        self.pushButton_71.setSizePolicy(sizePolicy)
        self.pushButton_71.setObjectName(_fromUtf8("pushButton_71"))
        self.verticalLayout_11.addWidget(self.pushButton_71)
        self.pushButton_72 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_72.sizePolicy().hasHeightForWidth())
        self.pushButton_72.setSizePolicy(sizePolicy)
        self.pushButton_72.setObjectName(_fromUtf8("pushButton_72"))
        self.verticalLayout_11.addWidget(self.pushButton_72)
        self.pushButton_73 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_73.sizePolicy().hasHeightForWidth())
        self.pushButton_73.setSizePolicy(sizePolicy)
        self.pushButton_73.setObjectName(_fromUtf8("pushButton_73"))
        self.verticalLayout_11.addWidget(self.pushButton_73)
        self.pushButton_74 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_74.sizePolicy().hasHeightForWidth())
        self.pushButton_74.setSizePolicy(sizePolicy)
        self.pushButton_74.setObjectName(_fromUtf8("pushButton_74"))
        self.verticalLayout_11.addWidget(self.pushButton_74)
        self.pushButton_75 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_75.sizePolicy().hasHeightForWidth())
        self.pushButton_75.setSizePolicy(sizePolicy)
        self.pushButton_75.setObjectName(_fromUtf8("pushButton_75"))
        self.verticalLayout_11.addWidget(self.pushButton_75)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pushButton_76 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_76.sizePolicy().hasHeightForWidth())
        self.pushButton_76.setSizePolicy(sizePolicy)
        self.pushButton_76.setObjectName(_fromUtf8("pushButton_76"))
        self.verticalLayout_12.addWidget(self.pushButton_76)
        self.pushButton_77 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_77.sizePolicy().hasHeightForWidth())
        self.pushButton_77.setSizePolicy(sizePolicy)
        self.pushButton_77.setObjectName(_fromUtf8("pushButton_77"))
        self.verticalLayout_12.addWidget(self.pushButton_77)
        self.pushButton_78 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_78.sizePolicy().hasHeightForWidth())
        self.pushButton_78.setSizePolicy(sizePolicy)
        self.pushButton_78.setObjectName(_fromUtf8("pushButton_78"))
        self.verticalLayout_12.addWidget(self.pushButton_78)
        self.pushButton_79 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_79.sizePolicy().hasHeightForWidth())
        self.pushButton_79.setSizePolicy(sizePolicy)
        self.pushButton_79.setObjectName(_fromUtf8("pushButton_79"))
        self.verticalLayout_12.addWidget(self.pushButton_79)
        self.pushButton_80 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_80.sizePolicy().hasHeightForWidth())
        self.pushButton_80.setSizePolicy(sizePolicy)
        self.pushButton_80.setObjectName(_fromUtf8("pushButton_80"))
        self.verticalLayout_12.addWidget(self.pushButton_80)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.pushButton_81 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_81.sizePolicy().hasHeightForWidth())
        self.pushButton_81.setSizePolicy(sizePolicy)
        self.pushButton_81.setObjectName(_fromUtf8("pushButton_81"))
        self.verticalLayout_13.addWidget(self.pushButton_81)
        self.pushButton_82 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_82.sizePolicy().hasHeightForWidth())
        self.pushButton_82.setSizePolicy(sizePolicy)
        self.pushButton_82.setObjectName(_fromUtf8("pushButton_82"))
        self.verticalLayout_13.addWidget(self.pushButton_82)
        self.pushButton_83 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_83.sizePolicy().hasHeightForWidth())
        self.pushButton_83.setSizePolicy(sizePolicy)
        self.pushButton_83.setObjectName(_fromUtf8("pushButton_83"))
        self.verticalLayout_13.addWidget(self.pushButton_83)
        self.pushButton_84 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_84.sizePolicy().hasHeightForWidth())
        self.pushButton_84.setSizePolicy(sizePolicy)
        self.pushButton_84.setObjectName(_fromUtf8("pushButton_84"))
        self.verticalLayout_13.addWidget(self.pushButton_84)
        self.pushButton_85 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_85.sizePolicy().hasHeightForWidth())
        self.pushButton_85.setSizePolicy(sizePolicy)
        self.pushButton_85.setObjectName(_fromUtf8("pushButton_85"))
        self.verticalLayout_13.addWidget(self.pushButton_85)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_88 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_88.sizePolicy().hasHeightForWidth())
        self.pushButton_88.setSizePolicy(sizePolicy)
        self.pushButton_88.setAcceptDrops(True)
        self.pushButton_88.setObjectName(_fromUtf8("pushButton_88"))
        self.gridLayout_2.addWidget(self.pushButton_88, 0, 3, 1, 1)
        self.pushButton_90 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_90.sizePolicy().hasHeightForWidth())
        self.pushButton_90.setSizePolicy(sizePolicy)
        self.pushButton_90.setAcceptDrops(True)
        self.pushButton_90.setObjectName(_fromUtf8("pushButton_90"))
        self.gridLayout_2.addWidget(self.pushButton_90, 0, 2, 1, 1)
        self.pushButton_94 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_94.sizePolicy().hasHeightForWidth())
        self.pushButton_94.setSizePolicy(sizePolicy)
        self.pushButton_94.setAcceptDrops(True)
        self.pushButton_94.setObjectName(_fromUtf8("pushButton_94"))
        self.gridLayout_2.addWidget(self.pushButton_94, 0, 5, 1, 1)
        self.pushButton_87 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_87.sizePolicy().hasHeightForWidth())
        self.pushButton_87.setSizePolicy(sizePolicy)
        self.pushButton_87.setAcceptDrops(True)
        self.pushButton_87.setObjectName(_fromUtf8("pushButton_87"))
        self.gridLayout_2.addWidget(self.pushButton_87, 0, 4, 1, 1)
        self.pushButton_93 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_93.sizePolicy().hasHeightForWidth())
        self.pushButton_93.setSizePolicy(sizePolicy)
        self.pushButton_93.setAcceptDrops(True)
        self.pushButton_93.setObjectName(_fromUtf8("pushButton_93"))
        self.gridLayout_2.addWidget(self.pushButton_93, 1, 5, 1, 1)
        self.pushButton_91 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_91.sizePolicy().hasHeightForWidth())
        self.pushButton_91.setSizePolicy(sizePolicy)
        self.pushButton_91.setAcceptDrops(True)
        self.pushButton_91.setObjectName(_fromUtf8("pushButton_91"))
        self.gridLayout_2.addWidget(self.pushButton_91, 0, 0, 1, 1)
        self.pushButton_89 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_89.sizePolicy().hasHeightForWidth())
        self.pushButton_89.setSizePolicy(sizePolicy)
        self.pushButton_89.setAcceptDrops(True)
        self.pushButton_89.setObjectName(_fromUtf8("pushButton_89"))
        self.gridLayout_2.addWidget(self.pushButton_89, 3, 5, 1, 1)
        self.pushButton_92 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_92.sizePolicy().hasHeightForWidth())
        self.pushButton_92.setSizePolicy(sizePolicy)
        self.pushButton_92.setAcceptDrops(True)
        self.pushButton_92.setObjectName(_fromUtf8("pushButton_92"))
        self.gridLayout_2.addWidget(self.pushButton_92, 4, 5, 1, 1)
        self.pushButton_105 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_105.sizePolicy().hasHeightForWidth())
        self.pushButton_105.setSizePolicy(sizePolicy)
        self.pushButton_105.setAcceptDrops(True)
        self.pushButton_105.setObjectName(_fromUtf8("pushButton_105"))
        self.gridLayout_2.addWidget(self.pushButton_105, 5, 5, 1, 1)
        self.pushButton_86 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_86.sizePolicy().hasHeightForWidth())
        self.pushButton_86.setSizePolicy(sizePolicy)
        self.pushButton_86.setAcceptDrops(True)
        self.pushButton_86.setObjectName(_fromUtf8("pushButton_86"))
        self.gridLayout_2.addWidget(self.pushButton_86, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOne = QtGui.QMenu(self.menubar)
        self.menuOne.setObjectName(_fromUtf8("menuOne"))
        self.menuTwo = QtGui.QMenu(self.menubar)
        self.menuTwo.setObjectName(_fromUtf8("menuTwo"))
        self.menuThree = QtGui.QMenu(self.menubar)
        self.menuThree.setObjectName(_fromUtf8("menuThree"))
        self.menuFour = QtGui.QMenu(self.menubar)
        self.menuFour.setObjectName(_fromUtf8("menuFour"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOneOne = QtGui.QAction(MainWindow)
        self.actionOneOne.setObjectName(_fromUtf8("actionOneOne"))
        self.actionOneTwo = QtGui.QAction(MainWindow)
        self.actionOneTwo.setObjectName(_fromUtf8("actionOneTwo"))
        self.menuOne.addAction(self.actionOneOne)
        self.menuOne.addAction(self.actionOneTwo)
        self.menubar.addAction(self.menuOne.menuAction())
        self.menubar.addAction(self.menuTwo.menuAction())
        self.menubar.addAction(self.menuThree.menuAction())
        self.menubar.addAction(self.menuFour.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_26)
        MainWindow.setTabOrder(self.pushButton_26, self.pushButton_27)
        MainWindow.setTabOrder(self.pushButton_27, self.pushButton_28)
        MainWindow.setTabOrder(self.pushButton_28, self.pushButton_29)
        MainWindow.setTabOrder(self.pushButton_29, self.pushButton_30)
        MainWindow.setTabOrder(self.pushButton_30, self.pushButton_21)
        MainWindow.setTabOrder(self.pushButton_21, self.pushButton_22)
        MainWindow.setTabOrder(self.pushButton_22, self.pushButton_23)
        MainWindow.setTabOrder(self.pushButton_23, self.pushButton_24)
        MainWindow.setTabOrder(self.pushButton_24, self.pushButton_25)
        MainWindow.setTabOrder(self.pushButton_25, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.pushButton_11)
        MainWindow.setTabOrder(self.pushButton_11, self.pushButton_12)
        MainWindow.setTabOrder(self.pushButton_12, self.pushButton_13)
        MainWindow.setTabOrder(self.pushButton_13, self.pushButton_14)
        MainWindow.setTabOrder(self.pushButton_14, self.pushButton_15)
        MainWindow.setTabOrder(self.pushButton_15, self.pushButton_16)
        MainWindow.setTabOrder(self.pushButton_16, self.pushButton_17)
        MainWindow.setTabOrder(self.pushButton_17, self.pushButton_18)
        MainWindow.setTabOrder(self.pushButton_18, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.pushButton_20)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "To", None))
        self.label.setText(_translate("MainWindow", "From", None))
        self.label_3.setText(_translate("MainWindow", "Subject", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Me", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "AnotherMe", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "ThirdMe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_26.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_27.setText(_translate("MainWindow", "vdtfbyhgmliv,dfb", None))
        self.pushButton_28.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_29.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_30.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_21.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_22.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_23.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_24.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_25.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_14.setText(_translate("MainWindow", "rsdtbyvseydrbtvtrdyvrdbfhyuj", None))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_17.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_18.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_19.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_20.setText(_translate("MainWindow", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.pushButton_31.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_35.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_32.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_34.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_33.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_66.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_67.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_68.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_69.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_70.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_61.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_62.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_63.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_64.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_65.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_71.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_72.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_73.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_74.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_75.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_76.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_77.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_78.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_79.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_80.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_81.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_82.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_83.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_84.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_85.setText(_translate("MainWindow", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Страница", None))
        self.pushButton_88.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_90.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_94.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_87.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_93.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_91.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_89.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_92.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_105.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_86.setText(_translate("MainWindow", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Страница", None))
        self.menuOne.setTitle(_translate("MainWindow", "One", None))
        self.menuTwo.setTitle(_translate("MainWindow", "Two", None))
        self.menuThree.setTitle(_translate("MainWindow", "Three", None))
        self.menuFour.setTitle(_translate("MainWindow", "Four", None))
        self.actionOneOne.setText(_translate("MainWindow", "OneOne", None))
        self.actionOneTwo.setText(_translate("MainWindow", "OneTwo", None))

